---
minVersion: '0.5.1'
github:
  owner: getsentry
  repo: sentry-electron
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: registry
    type: sdk
    config:
      canonical: 'npm:@sentry/electron'
  - name: github
    tagPrefix: v
